/**
 * LLM Integration for Repository Analysis
 *
 * This module provides functions for integrating with LLMs for repository analysis.
 */

import * as vscode from "vscode"
import * as fs from "fs"
import * as path from "path"
import { promisify } from "util"
import { DetectedLanguage, AnalysisResult, Recommendation } from "../types"

const readFile = promisify(fs.readFile)
const readdir = promisify(fs.readdir)

/**
 * LLM integration for repository analysis
 */
export class LlmIntegration {
	/**
	 * Generate a codebase summary using an LLM
	 * @param repoPath Path to the repository
	 * @param detectedLanguages Detected languages
	 * @param llmProfileId LLM profile ID
	 * @param token Cancellation token
	 * @returns Codebase summary
	 */
	async generateCodebaseSummary(
		repoPath: string,
		detectedLanguages: DetectedLanguage[],
		llmProfileId: string | undefined,
		token: vscode.CancellationToken,
	): Promise<string> {
		// If no LLM profile is selected, return a generic summary
		if (!llmProfileId) {
			return this.generateGenericSummary(detectedLanguages)
		}

		try {
			// In a real implementation, this would call the LLM API
			// For now, return a placeholder
			return `This is a placeholder codebase summary. In a real implementation, this would be generated by the LLM with profile ID "${llmProfileId}".`
		} catch (error) {
			console.error("Error generating codebase summary:", error)
			return this.generateGenericSummary(detectedLanguages)
		}
	}

	/**
	 * Assess code readability using an LLM
	 * @param repoPath Path to the repository
	 * @param detectedLanguages Detected languages
	 * @param languageAnalyses Language analysis results
	 * @param llmProfileId LLM profile ID
	 * @param token Cancellation token
	 * @returns Readability assessment
	 */
	async assessReadability(
		repoPath: string,
		detectedLanguages: DetectedLanguage[],
		languageAnalyses: Record<string, AnalysisResult>,
		llmProfileId: string | undefined,
		token: vscode.CancellationToken,
	): Promise<string> {
		// If no LLM profile is selected, return a generic assessment
		if (!llmProfileId) {
			return this.generateGenericReadabilityAssessment(languageAnalyses)
		}

		try {
			// In a real implementation, this would call the LLM API
			// For now, return a placeholder
			return `This is a placeholder readability assessment. In a real implementation, this would be generated by the LLM with profile ID "${llmProfileId}".`
		} catch (error) {
			console.error("Error assessing readability:", error)
			return this.generateGenericReadabilityAssessment(languageAnalyses)
		}
	}

	/**
	 * Generate recommendations using an LLM
	 * @param repoPath Path to the repository
	 * @param detectedLanguages Detected languages
	 * @param languageAnalyses Language analysis results
	 * @param llmProfileId LLM profile ID
	 * @param token Cancellation token
	 * @returns Recommendations
	 */
	async generateRecommendations(
		repoPath: string,
		detectedLanguages: DetectedLanguage[],
		languageAnalyses: Record<string, AnalysisResult>,
		llmProfileId: string | undefined,
		token: vscode.CancellationToken,
	): Promise<Recommendation[]> {
		// If no LLM profile is selected, return generic recommendations
		if (!llmProfileId) {
			return this.generateGenericRecommendations(languageAnalyses)
		}

		try {
			// In a real implementation, this would call the LLM API
			// For now, return placeholder recommendations
			return [
				{
					priority: "high",
					category: "code",
					message: `This is a placeholder recommendation. In a real implementation, this would be generated by the LLM with profile ID "${llmProfileId}".`,
				},
			]
		} catch (error) {
			console.error("Error generating recommendations:", error)
			return this.generateGenericRecommendations(languageAnalyses)
		}
	}

	/**
	 * Generate a generic codebase summary
	 * @param detectedLanguages Detected languages
	 * @returns Generic codebase summary
	 */
	private generateGenericSummary(detectedLanguages: DetectedLanguage[]): string {
		const languagesList = detectedLanguages
			.map((lang) => `${lang.name} (${Math.round(lang.percentage)}%)`)
			.join(", ")

		return `This codebase contains ${detectedLanguages.length} languages: ${languagesList}. 
    
A more detailed analysis would be provided by an LLM. Please configure an LLM profile to get a more comprehensive summary.`
	}

	/**
	 * Generate a generic readability assessment
	 * @param languageAnalyses Language analysis results
	 * @returns Generic readability assessment
	 */
	private generateGenericReadabilityAssessment(languageAnalyses: Record<string, AnalysisResult>): string {
		const averageScore =
			Object.values(languageAnalyses).reduce((sum, analysis) => sum + analysis.score, 0) /
			Object.values(languageAnalyses).length

		return `The codebase has an average readability score of ${averageScore.toFixed(1)} out of 10.
    
A more detailed assessment would be provided by an LLM. Please configure an LLM profile to get a more comprehensive readability assessment.`
	}

	/**
	 * Generate generic recommendations
	 * @param languageAnalyses Language analysis results
	 * @returns Generic recommendations
	 */
	private generateGenericRecommendations(languageAnalyses: Record<string, AnalysisResult>): Recommendation[] {
		const recommendations: Recommendation[] = []

		// Add recommendations based on analysis results
		for (const [language, analysis] of Object.entries(languageAnalyses)) {
			if (analysis.metrics.complexity < 5) {
				recommendations.push({
					priority: "high",
					category: "code",
					language,
					message: `Reduce code complexity in ${language} files.`,
				})
			}

			if (analysis.metrics.documentation < 5) {
				recommendations.push({
					priority: "medium",
					category: "documentation",
					language,
					message: `Improve documentation in ${language} files.`,
				})
			}

			if (analysis.metrics.structure < 5) {
				recommendations.push({
					priority: "medium",
					category: "structure",
					language,
					message: `Improve code structure in ${language} files.`,
				})
			}
		}

		// Add generic recommendations
		recommendations.push({
			priority: "low",
			category: "general",
			message: "Consider adding a comprehensive README.md file to help Claude understand the project.",
		})

		recommendations.push({
			priority: "low",
			category: "general",
			message: "Use consistent naming conventions across all files to improve readability.",
		})

		return recommendations
	}
}
